
export class pimsProfile {
  bp: string;
  bp_issue_date: string;
  bangla_name: string;
  english_name: string;
  father_name: string;
  mother_name: string;
  spouse_name: string;
  sex: string;
  date_of_birth: string;
  religion_name: string;
  marital_status: string;
  phone: string;
  alternative_phone_no: string | null;
  emergency_contact_no: string | null;
  email: string;
  present_rank: string;
  joining_rank: string;
  date_of_joining: string;
  retirement_date: string;
  date_of_joining_at_present_rank: string;
  employee_status: string;
  main_unit: string;
  main_unit_pid: number;
  unit: string;
  unit_pid: number;
  sub_unit: string;
  sub_unit_pid: number;
  sub_sub_unit: string | null;
  sub_sub_unit_pid: number | null;
  national_id: string;
  eight_passing_year: string | null;
  ssc_passing_year: string | null;
  hsc_passing_year: string | null;
  trainee_declaration_date: string | null;
  permanent_declaration_date: string | null;
  home_district: string;
  permanent_village: string;
  permanent_post: string;
  permanent_thana: string;
  permanent_district: string;
  permanent_division: string | null;
  permanent_zip: string | null;
  present_village: string;
  present_post: string;
  present_thana: string;
  present_district: string;
  present_division: string | null;
  present_zip: string | null;
  current_place_of_posting: string;
  picture: string;
}
